title: Saketh Ram Gangam # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Data Science professional with 4+ years of experience, specializing in applied Machine Learning, Strategy, and Analytics. 
  <br><br>
  MS Information Systems @ Northeastern University, Boston, USA
  <br><br>
  Data Scientist @ JerseySTEM
  Previously: <br>
  Data Scientist @ Abbott Labs, Boston <br>
  Data Scientist @ Ernst & Young
  <br><br>
  <a href="https://www.linkedin.com/in/sakethrgangam/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
